### PR TITLE
Add exercises for unstructured mesh as Jupyter notebook

### PR DESCRIPTION
**Pull request by sloede**
I created a Jupyter notebook from the `README.md` of the unstructured mesh tutorial.

@andrewwinters5000 can you please confirm that everthing looks ok and that the notebook actually works for you?

### CODE REVIEW

**Review by ranocha — CHANGES_REQUESTED** [review]
- You should add a cell instantiating the project in the main directory
- You should clear all output before uploading the notebook
- I got an error message when loading the notebook for the first time
- I get an error `unable to determine if out/solution_000180.vtu is accessible in the HDF5 format (file may not exist)` from `trixi2vtk("out/solution_000*", output_directory="out", nvisnodes=12)`
- The notebook doesn't cover everything from the README.md - that is on purpose? Maybe you could add a note that the remaining part is explained in the README.md?

**Comment by sloede** [comment]
Thanks a lot for your feedback!

>     * You should add a cell instantiating the project in the main directory

Done. 
>     * You should clear all output before uploading the notebook

Done.
>     * I got an error message when loading the notebook for the first time

Do you still get that error and could you post it here please?
>     * I get an error `unable to determine if out/solution_000180.vtu is accessible in the HDF5 format (file may not exist)` from `trixi2vtk("out/solution_000*", output_directory="out", nvisnodes=12)`

Should be fixed - could you please retry?
>     * The notebook doesn't cover everything from the README.md - that is on purpose? Maybe you could add a note that the remaining part is explained in the README.md?

Oops, that was an oversight... Could you point me to the part that's missing?

**Comment by ranocha** [comment]
> Do you still get that error and could you post it here please?

```
Notebook failed to load

The error was:
TypeError: ext.toLowerCase is not a function

See the error console for details.
```

**Comment by ranocha** [comment]
> Oops, that was an oversight... Could you point me to the part that's missing?

You stop at Exercise 2a. Thus, the remaining part is missing completely

**Comment by ranocha** [comment]
> > ```
> > * I get an error `unable to determine if out/solution_000180.vtu is accessible in the HDF5 format (file may not exist)` from `trixi2vtk("out/solution_000*", output_directory="out", nvisnodes=12)`
> > ```
> 
> 
> Should be fixed - could you please retry?

Yes, it works for me now :+1:

**Comment by sloede** [comment]
> > Oops, that was an oversight... Could you point me to the part that's missing?
> 
> You stop at Exercise 2a. Thus, the remaining part is missing completely. The last sentence I see is
> 
> > Now we are ready to generate an unstructured quadrilateral mesh that can be used by Trixi.

That must be an issue on your end, I think: https://nbviewer.jupyter.org/github/trixi-framework/tutorial-2021-icosahom/blob/exercise-in-jupyter/unstructured_mesh/exercises_unstructured_mesh.ipynb

**Comment by ranocha** [comment]
I never had such issues with Jupyter notebooks before. If it happens for me, chances are that others will get similar problems, too. Maybe it's related to the error message I get?

**Comment by ranocha** [comment]
Could you add HOHQMesh.jl to the Project.toml/Manifest.toml?

**Comment by ranocha** [comment]
Anyway, if I'm the only one getting this error we can go ahead and merge this. We will remember to tell people to look at the README.md when the notebook is broken for them, too

**Comment by sloede** [comment]
> > Do you still get that error and could you post it here please?
> 
> ```
> Notebook failed to load
> 
> The error was:
> TypeError: ext.toLowerCase is not a function
> 
> See the error console for details.
> ```

I tried to search the interwebs but couldn't find anything useful. Others have reported issues with Jupyter after upgrading their installation - did you do something like that recently? If not, could you maybe post the output of the error console?

**Comment by sloede** [comment]
> Could you add HOHQMesh.jl to the Project.toml/Manifest.toml?

Done in 8ca7a79/

**Comment by sloede** [comment]
> Anyway, if I'm the only one getting this error we can go ahead and merge this. We will remember to tell people to look at the README.md when the notebook is broken for them, too

Do you think it's necessary to keep the README if both nbviewer and the GH preview of the notebook work properly? TBH, I'd prefer to remove the README to retain a single source of truth.

**Comment by ranocha** [comment]
> I tried to search the interwebs but couldn't find anything useful. Others have reported issues with Jupyter after upgrading their installation - did you do something like that recently? If not, could you maybe post the output of the error console?

No, I didn't do anything like that. The other notebooks run fine and without any error on my system...

**Comment by ranocha** [comment]
Well, everything is fine after your latest update :partying_face:

**Comment by sloede** [comment]
> Well, everything is fine after your latest update partying_face

Thanks again for your feedback. I just ditched the now obsolete Markdown file for the unstructured tutorial. If @andrewwinters5000 agrees, feel free to merge this PR. It still uses HOHQMesh v1.0.0 (since the new package seems not to be picked up by the Pkg servers yet), but since we don't need the newest version for these exercises, I think we're good to go.

**Comment by ranocha** [comment]
I added code to remove the margins of the Jupyter notebook. This makes it a bit easier to read the output of HOHQMesh (which is quite wide)

**Review by ranocha — APPROVED** [review]

**Comment by ranocha** [comment]
@andrewwinters5000 Feel free to merge this PR if everything looks good to you

**Comment by andrewwinters5000** [comment]
LGTM! Thanks @sloede for converting this into a Jupyter notebook

**Pull request merged**
